version: "3.8"

services:
  nextjs:
    build: ./ostoja-strona/
    ports:
      - "2000:2000"
    environment:
      NODE_ENV: production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
