version: "3.8"

services:
  nextjs:
    build: ./ostoja-strona/
    ports:
      - "2000:2000"
    environment:
      NODE_ENV: production
    networks:
      - app-network
      
  strapi:
    build: ./ostoja-cms/
    ports:
      - "2337:2337"
    env_file: ./ostoja-cms/.env
    environment:
      NODE_ENV: production
    volumes:
      - ./ostoja-cms/.env:/opt/app/.env
      - ./ostoja-cms/public/uploads:/opt/app/public/uploads
      - ./ostoja-cms/data:/opt/app/data
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - nextjs
      - strapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
