version: "3.8"

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /root/certs:/etc/nginx/certs:ro
    depends_on:
      - nextjs
